routes/web.php
<?php

use Illuminate\Support\Str;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TodoController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoryTodosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', HomeController::class)->name('home');
Route::get('category/{slug}/todos', CategoryTodosController::class)->name('category.todos');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware(['auth'])->group(function () {
    // todos
    Route::resource('todos', TodoController::class)->except('show');
    Route::put('todos/{todo}/complete', [TodoController::class, 'complete'])->name('todos.complete');

    //categories
    Route::resource('categories', CategoryController::class)->except('show');
});

require __DIR__.'/auth.php';

app/Models/Todo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Todo extends Model
{
    use HasFactory , SoftDeletes;

    protected $fillable = [
        'todo',
        'image',
    ];

    public function Categories ()
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TodoRequest;
use App\Models\Category;
use App\Models\Todo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class TodoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['todos'] = Todo::with('Categories')->get();
        return view('todo.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['categories'] = Category::pluck('name','id');
        return view('todo.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TodoRequest $request)
    {
        $path = "";
        if($request->hasFile('image')){
            $fileName = Str::snake($request->get('todo')).'.'.$request->file('image')->getClientOriginalExtension();
            $path = Storage::putFileAs('image/todos',$request->file('image'), $fileName);

        }
        $todo = Todo::create([
            'todo' => $request->get('todo'),
            'image' => $path,
        ]);

        if(empty($todo)){
            return redirect()->back()->withInput();
        }

        $todo->categories()->attach($request->get('categories'));

        return redirect()
        ->route('todos.index')
        ->with('SUCCESS', __('Todo has been created.'));
    }

    /**
     * Complete the specified resource.
     *
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function complete(Todo $todo)
    {
        $todo->forceFill([
            'is_complete' => true,
        ]);
        if($todo->update()){
        return redirect()->route('todos.index')->with('SUCCESS', __('Task done.'));
        }
        return redirect()->back()->withInput()->with('ERROR', __('Fail to complete.'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function edit(Todo $todo)
    {
        $data['todo'] = $todo;
        $data['categories'] = Category::pluck('name','id');
        return view('todo.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function update(TodoRequest $request, Todo $todo)
    {
        $todo->todo = $request->get('todo');

        if($request->hasFile('image')){
            if($todo->image){
                Storage::delete($todo->image);
            }
            $fileName = Str::snake($request->get('todo')).'.'.$request->file('image')->getClientOriginalExtension();
            $todo->image = Storage::putFileAs('image/todos',$request->file('image'), $fileName);
        }

        if($todo->update()){
            $todo->categories()->sync($request->get('categories'));
            return redirect()->route('todos.index')->with('SUCCESS', __('Todo has been Updated.'));
        }
        return redirect()->back()->withInput()->with('ERROR', __('Fail to Updated.'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Todo $todo)
    {
        if($todo->image){
            Storage::delete($todo->image);
        }
        if($todo->delete()){
            $todo->categories()->detach();
            return redirect()->back()->with('SUCCESS', __('Todo has been deleted.'));
        }
        return redirect()->back()->with('ERROR', __('Please try again.'));


    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/todo/_form.blade.php
<div class="mb-4">
    <label class="block" for="category">Category</label>
    <select name="categories[]" id="category_id" multiple="true">
        <option value="">{{ __("Select Category")}}</option>
        @foreach ($categories as $id => $name)
            <option @isset($todo)
                        {{$todo->Categories->firstWhere("name",$name) ? "selected=true" : ""}}
                    @endisset value="{{ $id }}" >
                {{ $name }}
            </option>
        @endforeach
    </select>
    <p class=" text-red-500">{{$errors->first("categories")}}</p>
</div>
<div class="mb-4">
    <label class="block" for="task">Task</label>
    <input class="focus" type="text" name="todo" value="{{ old('todo', isset($todo) ? $todo->todo : '')}}" id="todo">
    <p class=" text-red-500">{{$errors->first("todo")}}</p>
</div>
<div class="mb-4">
    <label class="block" for="task">Image</label>
    <input class="focus" type="file" name="image" id="image">
    <p class=" text-red-500">{{$errors->first("image")}}</p>
</div>
<div>
    <a class="p-1 pl-3 pr-3 bg-transparent border-2 border-gray-500 text-gray-500 text-lg rounded-lg hover:bg-gray-500 hover:text-gray-100 focus:border-4 focus:border-gray-300" href="{{ route('todos.index')}}">Back</a>

    <button class="p-1 pl-7 pr-7 bg-transparent border-2 border-green-500 text-green-500 text-lg rounded-lg hover:bg-green-500 hover:text-gray-100 focus:border-4 focus:border-green-300" type="submit">{{$buttonText}}</button>
</div>

resources/views/todo/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Todo') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("todos.store")}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @include("todo._form",["buttonText" => __("Create")])

                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/todo/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Todo') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route("todos.update", $todo->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method("PUT")
                        @include("todo._form",["buttonText" => __("Update")])
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/todo/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Todo List') }}
            </h2>
            <a class="px-2 py-1 font-semibold leading-tight text-blue-700 bg-blue-100 rounded-sm" href="{{ route('todos.create')}}">Create Task</a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="w-full">
                        <thead>
                          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                            <th class="px-4 py-3">ID</th>
                            <th class="px-4 py-3">Category</th>
                            <th class="px-4 py-3">Todo</th>
                            <th class="px-4 py-3">Image</th>
                            <th class="px-4 py-3">Status</th>
                            <th class="px-4 py-3">Action</th>
                          </tr>
                        </thead>
                        <tbody class="bg-white">
                          @forelse ($todos as $todo)
                          <tr class="text-gray-700">
                            <td class="px-4 py-3 border">{{ $todo->id}}</td>
                            <td class="px-4 py-3 border">{{ $todo->Categories->pluck('name')->join(', ')}}</td>
                            <td class="px-4 py-3 text-ms font-semibold border">{{$todo->todo}}</td>
                            <td class="px-4 py-3 text-xs border">
                                <img width="50" src="{{ asset($todo->image)}}" alt="image">
                            </td>
                            <td class="px-4 py-3 text-xs border">
                                @if ($todo->is_complete)
                                    <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm"> Completed </span>
                                @else
                                <span class="px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-sm"> Incomplete </span>
                                @endif
                            </td>
                            <td class="py-3 px-4 border">
                                @if (!$todo->is_complete)
                                <a class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm complete-todo" href="{{ route('todos.complete', $todo->id)}}">Complete</a>

                                @endif
                                <a class="px-2 py-1 font-semibold leading-tight text-yellow-700 bg-yellow-100 rounded-sm" href="{{ route('todos.edit', $todo->id)}}">Edit</a>
                                <a href="{{route('todos.destroy', $todo->id)}}" class="delete-row px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-sm" data-confirm="Are You Sure To Delete This?"> Delete </a>

                            </td>
                          </tr>
                          @empty
                          <tr>
                            <td colspan="4" class="px-4 py-3 text-center">{{ __("No todo found.")}}</td>
                        </tr>
                          @endforelse
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>